package wroclaw.mpk.synchro.structure;

import java.io.Serializable;

public enum LineName implements Serializable {

    POSWIETNE_1, BISKUPIN_1, KRZYKI_2, BISKUPIN_2, LESNICA_3, KSIEZE_3, BISKUPIN_4, OPOROW_4, KSIEZE_5, OPOROW_5, KOWALE_6, KRZYKI_6, KLECINA_7, POSWIETNE_7, TARNOGAJ_8, KARLOWICE_8, PARK_9, SEPOLNO_9, NADODRZE_0L, NADODRZE_0P, LESNICA_10, BISKUPIN_10, KROMERA_11, GRABISZYNSKA_CM_11, FAT_14, OSOBOWICE_14, PARK_15, POSWIETNE_15, KLECINA_17, SEPOLNO_17, LESNICA_20, OPOROW_20, WPP_23, KROMERA_23, FAT_24, OSOBOWICE_24, GAJ_31, ST_WROCLAW_31, GAJ_32, KOZANOW_32, PILCZYCE_33, SEPOLNO_33
//    , OPOROW_E1, OPOROW_E1Q, OSOBOWICE_E1, OSOBOWICE_E1Q, KRZYKI_E2, KRZYKI_E2Q, OSOBOWICE_E2, OSOBOWICE_E2Q, OSOBOWICE_E3, OSOBOWICE_E3Q, SEPOLNO_E3, SEPOLNO_E3Q, OSOBOWICE_E4, OSOBOWICE_E4Q, KROMERA_E4, KROMERA_E4Q, OSOBOWICE_E5, OSOBOWICE_E5Q, BISKUPIN_E5, BISKUPIN_E5Q, SEPOLNO_E6, SEPOLNO_E6Q, OPOROW_E6, OPOROW_E6Q, GRABISZYNSKA_CM_E7, GRABISZYNSKA_CM_E7Q, PILCZYCE_E7, PILCZYCE_E7Q, OSOBOWICE_E8, OSOBOWICE_E8Q, GAJ_E8, GAJ_E8Q, OSOBOWICE_E9, OSOBOWICE_E9Q, GRABISZYNSKA_CM_E9, GRABISZYNSKA_CM_E9Q


}
