package wroclaw.mpk.synchro.structure;

import java.io.Serializable;

public enum NodeName implements Serializable {

    BISKUPIN, SEPOLNO, PILCZYCE, TARNOGAJ, LEGIONOW, KSIEZE, KARLOWICE, KLECINA, ST_WROCLAW, JPII, KOWALE, PARK, OLIMPIJSKI, NADODRZE, WPP, LESNICA, KRZYKI, OPOROW, DOMINIKANSKA, ARKADY, POSWIETNE, KOZANOW, ORLAT, GAJ, GLOWNY, AUTOBUSOWY, OSOBOWICE, STASZICA, GRUNWALDZKI, GRABISZYNSKA_CM, FAT, KROMERA, BEMA, PRZYJAZNI

}
